name: Auto approve and Merge Dependabot PRs
on:
  pull_request_target:
    types: [labeled]
permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    name: Auto-approve dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo at pull request
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Create local changes - install dependencies
      run: npm ci
    - name: Commit & Push Changes
      uses: actions-js/push@v1.4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: 'refs/heads/${{ github.event.pull_request.head.ref }}'
    - uses: hmarr/auto-approve-action@v4
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
