on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get Release Notes
        run: |
          echo "$(git tag -l --sort=taggerdate --format="%(contents:subject)" | tail -n 1)" > RELEASE_NOTES
          echo "This release corresponds to the latest of the same major version for the SAF CLI." >> RELEASE_NOTES
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES
          draft: true
