name: Provide a few examples
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo to have access to test data
      uses: actions/checkout@v3
    - name: Test scan
      uses: mitre/saf_action@main
      with:
        command_string: 'scan'
    - name: Test validate threshold with -T
      uses: mitre/saf_action@main
      with:
        command_string: 'validate threshold -i ./test/sample_data/red_hat_good.json -T "{\\"error.total\\": 0, \\"compliance.min\\": 50}"'
    - name: Test validate threshold with -T with a space in the path
      uses: mitre/saf_action@main
      with:
        command_string: 'validate threshold -i ./test/sample_data/red_hat_good\\ with_space.json -T "{\\"error.total\\": 0, \\"compliance.min\\": 50}"'
