name: Provide a few examples
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Test help
      uses: mitre/saf_action@main
      with:
        command_string: '-h'
