name: Provide a few examples
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: where is the action?
      run: find /
    - name: Checkout repo at pull request
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Test scan
      uses: mitre/saf_action@main
      with:
        command_string: 'scan'
